name: Frontend Development

on:
  push:
    paths:
      - "frontend/**"
    branches-ignore:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache-dependency-path: "./frontend/package-lock.json"
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run prettier

      - name: Run Lint
        run: npm run lint

      - name: Build app
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: deploy-artifact
          path: ./frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Download production artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy-artifact
          path: ./frontend/build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Deploy to S3
        run: aws s3 sync . s3://expense-echo-app --acl public-read
        working-directory: frontend/dist
