name: Backend Development

on:
  push:
    branches-ignore:
      - "main"

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    env:
      DB_CONNECTION_URL: ${{ secrets.DB_CONNECTION_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Maven Package
        run: mvn -B clean package -DskipTests

      - name: Maven Verify
        run: mvn -B clean verify

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: deploy-artifact
          path: ./backend/target

  publish-image:
    name: Publish app image to DockerHub
    needs: [build-test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Download deploy artifact
        uses: actions/download-artifact@v3
        with:
          name: deploy-artifact
          path: ./backend/target

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: leonardoan/expense-echo-spring-boot:latest

  deploy:
    name: Deploy to Render
    needs: [build-test, publish-image]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
